[2025-02-17T00:08:04.796+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-17T00:08:04.809+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer scheduled__2025-02-16T00:00:00+00:00 [queued]>
[2025-02-17T00:08:04.817+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer scheduled__2025-02-16T00:00:00+00:00 [queued]>
[2025-02-17T00:08:04.818+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-17T00:08:04.827+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): rabbitmq_consumer> on 2025-02-16 00:00:00+00:00
[2025-02-17T00:08:04.835+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=17073) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-17T00:08:04.836+0000] {standard_task_runner.py:72} INFO - Started process 17074 to run task
[2025-02-17T00:08:04.837+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'rabbitmq_consumer', 'scheduled__2025-02-16T00:00:00+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmpfr70hyr2']
[2025-02-17T00:08:04.837+0000] {standard_task_runner.py:105} INFO - Job 326: Subtask rabbitmq_consumer
[2025-02-17T00:08:04.868+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.rabbitmq_consumer scheduled__2025-02-16T00:00:00+00:00 [running]> on host 3aa1f743f988
[2025-02-17T00:08:04.918+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='rabbitmq_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-16T00:00:00+00:00'
[2025-02-17T00:08:04.919+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-17T00:08:04.919+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-17T00:08:04.919+0000] {logging_mixin.py:190} INFO - Current task name:rabbitmq_consumer state:running start_date:2025-02-17 00:08:04.810216+00:00
[2025-02-17T00:08:04.919+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-02-17T00:08:04.920+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-17T00:08:04.923+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.19.0.9', 5672)
[2025-02-17T00:08:04.928+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=93, family=2, type=1, proto=6, laddr=('172.19.0.6', 42814), raddr=('172.19.0.9', 5672)>
[2025-02-17T00:08:04.930+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0xffff605b2fc0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0xffff605b2fc0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-02-17T00:08:04.959+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0xffff605b2fc0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-17T00:08:04.960+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0xffff605b2fc0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-17T00:08:04.960+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0xffff605b2fc0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-02-17T00:08:04.960+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-02-17T00:08:04.968+0000] {logging_mixin.py:190} INFO - Queue create-vm has 0 messages
[2025-02-17T00:08:04.970+0000] {logging_mixin.py:190} INFO - Listening for messages in queue: create-vm
[2025-02-17T00:24:31.412+0000] {job.py:229} INFO - Heartbeat recovered after 930.75 seconds
[2025-02-17T00:40:26.696+0000] {job.py:229} INFO - Heartbeat recovered after 929.96 seconds
[2025-02-17T00:53:58.065+0000] {job.py:229} INFO - Heartbeat recovered after 760.74 seconds
[2025-02-17T00:55:42.718+0000] {job.py:229} INFO - Heartbeat recovered after 79.29 seconds
[2025-02-17T01:02:08.046+0000] {job.py:229} INFO - Heartbeat recovered after 325.13 seconds
[2025-02-17T01:27:38.889+0000] {job.py:229} INFO - Heartbeat recovered after 843.06 seconds
[2025-02-17T01:27:43.984+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2025-02-17T01:27:43.992+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-17T01:27:44.003+0000] {process_utils.py:132} INFO - Sending 15 to group 17074. PIDs of all processes in the group: [17074]
[2025-02-17T01:27:44.004+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 17074
[2025-02-17T01:27:44.006+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-17T01:27:44.028+0000] {channel.py:536} INFO - Closing channel (0): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0xffff605b2fc0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>>
[2025-02-17T01:27:44.030+0000] {channel.py:1133} INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0xffff605b2fc0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>>
[2025-02-17T01:27:44.033+0000] {blocking_connection.py:802} INFO - Closing connection (200): Normal shutdown
[2025-02-17T01:27:44.034+0000] {connection.py:1316} INFO - Closing connection (200): 'Normal shutdown'
[2025-02-17T01:27:44.035+0000] {io_services_utils.py:731} INFO - Aborting transport connection: state=1; <socket.socket fd=93, family=2, type=1, proto=6, laddr=('172.19.0.6', 42814), raddr=('172.19.0.9', 5672)>
[2025-02-17T01:27:44.037+0000] {io_services_utils.py:904} INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=93, family=2, type=1, proto=6, laddr=('172.19.0.6', 42814), raddr=('172.19.0.9', 5672)>
[2025-02-17T01:27:44.037+0000] {io_services_utils.py:869} INFO - Deactivating transport: state=1; <socket.socket fd=93, family=2, type=1, proto=6, laddr=('172.19.0.6', 42814), raddr=('172.19.0.9', 5672)>
[2025-02-17T01:27:44.038+0000] {connection.py:2017} INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
[2025-02-17T01:27:44.038+0000] {connection.py:2086} INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
[2025-02-17T01:27:44.051+0000] {io_services_utils.py:882} INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=93, family=2, type=1, proto=6, laddr=('172.19.0.6', 42814), raddr=('172.19.0.9', 5672)>
[2025-02-17T01:27:44.054+0000] {blocking_connection.py:525} INFO - User-initiated close: result=(<SelectConnection CLOSED transport=None params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>, ConnectionClosedByClient: (200) 'Normal shutdown')
[2025-02-17T01:27:44.062+0000] {logging_mixin.py:190} INFO - Listener stopped.
[2025-02-17T01:27:44.063+0000] {python.py:240} INFO - Done. Returned value was: 
[2025-02-17T01:27:44.131+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-17T01:27:44.132+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=idp, task_id=rabbitmq_consumer, run_id=scheduled__2025-02-16T00:00:00+00:00, execution_date=20250216T000000, start_date=20250217T000804, end_date=20250217T012744
[2025-02-17T01:27:44.159+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-17T01:27:44.159+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-17T01:27:44.159+0000] {logging_mixin.py:190} INFO - Dag name:idp queued_at:2025-02-17 00:08:01.799450+00:00
[2025-02-17T01:27:44.159+0000] {logging_mixin.py:190} INFO - Task hostname:3aa1f743f988 operator:PythonOperator
[2025-02-17T01:27:44.234+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=17074, status='terminated', exitcode=0, started='00:08:04') (17074) terminated with exit code 0
