[2025-02-07T07:48:57.536+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T07:48:57.545+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T07:48:55.168005+00:00 [queued]>
[2025-02-07T07:48:57.549+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T07:48:55.168005+00:00 [queued]>
[2025-02-07T07:48:57.550+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-07T07:48:57.561+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): rabbitmq_consumer> on 2025-02-07 07:48:55.168005+00:00
[2025-02-07T07:48:57.568+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=402) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T07:48:57.569+0000] {standard_task_runner.py:72} INFO - Started process 403 to run task
[2025-02-07T07:48:57.569+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'rabbitmq_consumer', 'manual__2025-02-07T07:48:55.168005+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmp2w0fuvrd']
[2025-02-07T07:48:57.571+0000] {standard_task_runner.py:105} INFO - Job 250: Subtask rabbitmq_consumer
[2025-02-07T07:48:57.601+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T07:48:55.168005+00:00 [running]> on host 3aa1f743f988
[2025-02-07T07:48:57.650+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='rabbitmq_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T07:48:55.168005+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T07:48:55.168005+00:00'
[2025-02-07T07:48:57.652+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T07:48:57.652+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T07:48:57.652+0000] {logging_mixin.py:190} INFO - Current task name:rabbitmq_consumer state:running start_date:2025-02-07 07:48:57.546033+00:00
[2025-02-07T07:48:57.652+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-02-07T07:48:57.653+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T07:48:57.654+0000] {logging_mixin.py:190} INFO - RABBITMQ_URL: amqp://rabbitmq:rabbitmq@localhost:5672
[2025-02-07T07:48:57.654+0000] {logging_mixin.py:190} INFO - RabbitMQ Host: localhost
[2025-02-07T07:48:57.655+0000] {logging_mixin.py:190} INFO - RabbitMQ Port: 5672
[2025-02-07T07:48:57.656+0000] {blocking_connection.py:457} ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/utils/connection_workflow.py", line 638, in start
    iter(connection_configs)
TypeError: 'AMQPConnectionWorkflow' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 439, in _create_connection
    impl_class.create_connection(
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/select_connection.py", line 131, in create_connection
    return cls._start_connection_workflow(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/base_connection.py", line 180, in _start_connection_workflow
    workflow.start(
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/utils/connection_workflow.py", line 640, in start
    raise TypeError(
TypeError: connection_configs does not support iteration: TypeError("'AMQPConnectionWorkflow' object is not iterable")
[2025-02-07T07:48:57.658+0000] {logging_mixin.py:190} INFO - Error in listener: connection_configs does not support iteration: TypeError("'AMQPConnectionWorkflow' object is not iterable")
[2025-02-07T07:48:57.659+0000] {logging_mixin.py:190} INFO - Listener stopped.
[2025-02-07T07:48:57.659+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-07T07:48:57.664+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T07:48:57.664+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=idp, task_id=rabbitmq_consumer, run_id=manual__2025-02-07T07:48:55.168005+00:00, execution_date=20250207T074855, start_date=20250207T074857, end_date=20250207T074857
[2025-02-07T07:48:57.669+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-07T07:48:57.669+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-07T07:48:57.669+0000] {logging_mixin.py:190} INFO - Dag name:idp queued_at:2025-02-07 07:48:55.178800+00:00
[2025-02-07T07:48:57.669+0000] {logging_mixin.py:190} INFO - Task hostname:3aa1f743f988 operator:PythonOperator
[2025-02-07T07:48:57.711+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T07:48:57.724+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-07T07:48:57.725+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
