[2025-01-31T07:46:40.350+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T07:46:40.374+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.load_requests manual__2025-01-27T13:47:21.551348+00:00 [queued]>
[2025-01-31T07:46:40.385+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.load_requests manual__2025-01-27T13:47:21.551348+00:00 [queued]>
[2025-01-31T07:46:40.385+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-31T07:46:40.397+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_requests> on 2025-01-27 13:47:21.551348+00:00
[2025-01-31T07:46:40.464+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'load_requests', 'manual__2025-01-27T13:47:21.551348+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmpp1ux7fii']
[2025-01-31T07:46:40.464+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=87) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T07:46:40.467+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask load_requests
[2025-01-31T07:46:40.469+0000] {standard_task_runner.py:72} INFO - Started process 94 to run task
[2025-01-31T07:46:40.549+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.load_requests manual__2025-01-27T13:47:21.551348+00:00 [running]> on host ad0831fca39a
[2025-01-31T07:46:40.650+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='load_requests' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T13:47:21.551348+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-27T13:47:21.551348+00:00'
[2025-01-31T07:46:40.652+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-31T07:46:40.652+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-31T07:46:40.653+0000] {logging_mixin.py:190} INFO - Current task name:load_requests state:running start_date:2025-01-31 07:46:40.376581+00:00
[2025-01-31T07:46:40.653+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-01-31T07:46:40.654+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T07:46:40.655+0000] {logging_mixin.py:190} INFO - MongoDB connection failed: 'MONGODB_URI'
[2025-01-31T07:46:40.656+0000] {python.py:240} INFO - Done. Returned value was: []
[2025-01-31T07:46:40.678+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T07:46:40.679+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=idp, task_id=load_requests, run_id=manual__2025-01-27T13:47:21.551348+00:00, execution_date=20250127T134721, start_date=20250131T074640, end_date=20250131T074640
[2025-01-31T07:46:40.688+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-31T07:46:40.688+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-31T07:46:40.689+0000] {logging_mixin.py:190} INFO - Dag name:idp queued_at:2025-01-27 13:47:21.697197+00:00
[2025-01-31T07:46:40.689+0000] {logging_mixin.py:190} INFO - Task hostname:ad0831fca39a operator:PythonOperator
[2025-01-31T07:46:40.698+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T07:46:40.718+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-31T07:46:40.720+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
